rly_file = "Enoshima_Railway.rly"
ttb_files = [ "Enoshima_Week_2021.ttb",]
ssn_files = []
country_code = "JP"
name = "Enoshima Electric Railway/Enoden Line"
description = "Private railway line running from Kamakura to Fujisawa in Japan"
display_name = "Enoshima Railway"
author = "Krizar"
contributors = []
