rly_file = "Enoshima_Railway.rly"
ttb_files = [ "Enoshima_Week_2021.ttb",]
ssn_files = []
country_code = "JP"
name = "Enoshima Electric Railway/Enoden Line"
description = "Privately run railway line running from Kamakura to Fujisawa in Japan"
display_name = "Enoshima Railway"
author = "Krizar"
contributors = []
graphic_files = [ "native_shichirigahama.PNG", "native_ishigami.PNG", "native_koshigoe.PNG", "native_kugenuma.PNG", "native_kamakura.PNG", "native_enoshima.PNG", "native_shonankaigankoen.PNG", "native_wadazuka.PNG", "native_gokurakuji.PNG", "native_yanagikoji.PNG", "native_kamakurakokomae.PNG", "native_inamuragasaki.PNG", "native_title.PNG", "native_hase.PNG", "native_yuigahama.PNG", "native_fujisawa.PNG",]
minimum_required = "2.4.0"
img_files = [ "Enoshima.bmp",]
doc_files = [ "README.pdf", "README.md",]
release_date = "2022-02-23"
version = "1.0.0"
factual = true
