name: Remove old artifacts

on:
  schedule:
    # Every day at 9pm
    - cron: '0 21 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '360 seconds'
